version: "3"

services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
  backend:
    container_name: opengpts-backend
    image: docker.io/langchain/open-gpts:latest
    ports:
      - "8100:8000" # Backend is accessible on localhost:8100 and serves the frontend
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "postgres"
